apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: "{{ .Chart.Name }}"
  labels:
    app: "{{ .Chart.Name }}"
spec:
  replicas: {{ .Values.lobby.replicaCount }}
  selector:
    matchLabels:
      app: "{{ .Chart.Name }}"
  template:
    metadata:
      labels:
        app: "{{ .Chart.Name }}"
    spec:
      containers:
      - name: "{{ .Chart.Name }}"
        image: "{{ .Values.lobby.image.repository }}:{{ .Values.lobby.image.tag }}"
        imagePullPolicy: {{ .Values.lobby.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.lobby.service.port }}
