services:
  semarb5_game_room_dev:
    container_name: semarb5_game_room_dev
    restart: no
    build:
      context: gameroom/.
      dockerfile: Dockerfile.local
    ports:
      - 5000:5000
    volumes:
      - ./gameroom/:/app

  semarb5_game_lobby_dev:
    container_name: semarb5_game_lobby_dev
    restart: no
    build:
      context: gamelobby/.
      dockerfile: Dockerfile.local
    ports:
      - 80:80
    volumes:
      - ./gamelobby/:/app
