namespace: pong-game-lobby

lobby:
  replicaCount: 1

  image:
    repository: ghcr.io/euthal02/pong-gamelobby
    tag: latest
    pullPolicy: Always

  service:
    port: 80
    targetport: 80
    protocol: TCP
    type: NodePort

  ingress:
    enabled: true
    hostname: lobby.semesterarbeit.com
    className: alb
    annotations:
      external-dns.alpha.kubernetes.io/hostname: lobby.semesterarbeit.com
      alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-2:207567766378:certificate/1e7f31ea-1d4d-4e60-b62e-048ff6c6ba6d
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
      alb.ingress.kubernetes.io/healthcheck-path: /health
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
      alb.ingress.kubernetes.io/load-balancer-attributes: 'idle_timeout.timeout_seconds=3600'
    tls:
      enabled: true
      secretName: lobby-semesterarbeit-com
      hostname: lobby.semesterarbeit.com


resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
