# Base python package
FROM python:3.12-slim

# Working directory
WORKDIR /app

# add files
ADD . /app

# Install requirements 
RUN pip install -r requirements.txt

# for flask web server
EXPOSE 5000

# This is the runtime command for the container
CMD [ "python3", "wsgi.py" ]
